name: Run test

on: [push]

jobs:
  build:
  

    runs-on: ubuntu-latest
    permissions:
      checks: write
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with unittest
        run: |
          cd pbix_doc
          python -m xmlrunner discover ./tests/ -o ./test_results/ -vvv
      - name: JUnit Report Action
        # You may pin to the exact commit or the version.
        # uses: mikepenz/action-junit-report@4fa23552acda20a6a1d44f16224a90efbeb6c5f1
        uses: mikepenz/action-junit-report@v3.7.5
        with:
            report_paths: '**/test-results/TEST-*.xml'
